sudo: required
os:
  - osx
  - linux
env:
  global:
    - PONY_VERSION=$(date +%Y%m%d)
services:
- docker
install:
- bash install.sh
before_script:
- bash before_script.sh
script:
- bash script.sh
branches:
  only:
    - master
