sudo: required
env:
  global:
    - PONY_VERSION=$(date +%Y_%m_%d)
services:
- docker
install:
- bash install.sh
before_script:
- bash before_script.sh
script:
- bash script.sh
branches:
  only:
    - master
