version: 1.0.{build}
image: Visual Studio 2015
artifacts:
  - path: C:\projects\ponyc\work\vs2015\..\..\build\release\
    name: ponyc.zip
environment:
  BINTRAY_TOKEN:
    secure: ygxH+xCHwlCcWSfI557fhQVCQ6IcjwkAlz5dPTr6VJNmoi/6vuz1bekC+SLL9ToX
  BINTRAY_USER:
    secure: PpL/fbiTGRPEhjjcjoQjxg==
  matrix:
    - llvm: 3.8.0
configuration:
  - Release
cache:
  - C:\LLVM-%llvm%\ -> .appveyor.yml
  - C:\premake5.exe -> .appveyor.yml
  - C:\ponyc-windows-libs\ -> .appveyor.yml
clone_depth: 2
clone_folder: C:\projects\ponyc-nighly
install:
  - ps: C:\projects\ponyc-nighly\windows\install.ps1
before_build:
  - ps: C:\projects\ponyc-nighly\windows\before_build.ps1
build:
  project: C:\projects\ponyc\work\vs2015\ponyc.sln
  verbosity: minimal
test_script:
  - ps: C:\projects\ponyc-nighly\windows\test_script.ps1
on_success:
  - ps: C:\projects\ponyc-nighly\windows\on_success.ps1